name: blockchain-infra
include:
  - compose/base.yml
  - examples/compose.yml
services:
  ctf-server-orchestrator:
    restart: unless-stopped
    container_name: blockchain-infra-orchestrator
    image: ghcr.io/es3n1n/paradigmctf.py:latest
    build: .
    user: root
    command: uvicorn ctf_server:orchestrator --host 0.0.0.0 --port 7283 --workers 11
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "7283:7283"
    environment:
      - BACKEND=docker
      - DATABASE=redis
      - REDIS_URL=redis://database:6379/0
    networks:
      ctf_network:
        aliases:
          - orchestrator
    depends_on:
      - database
